import streamlit as st
import pandas as pd

st.set_page_config(layout="wide")
with open("css/style.css") as source_des:
    st.markdown(f"<style>{source_des.read()}</style>", unsafe_allow_html=True)
    st.markdown("")
    st.header("Metadata")

    st.subheader("Identitas Usaha")
    st.text("a. idsbr")
    st.text("b. nama_usaha")
    st.text("c. alamat")
    st.text("d. nama_sls")
    st.text("e. kodepos")
    st.text("f. nomor_telepon")
    st.text("g. nomor_whatsapp")
    st.text("h. email")
    st.text("i. website")
    st.text("j. latitude")
    st.text("k. longitude")
    
    st.subheader("Keberadaan Usaha/Perusahaan")
    st.text("a. keberadaan_usaha")
    st.markdown("&emsp; &emsp; 1. Aktif")
    st.markdown("&emsp; &emsp; 2. Tutup Sementara")
    st.markdown("&emsp; &emsp; 3. Belum Beroperasi/Berproduksi")
    st.markdown("&emsp; &emsp; 4. Tutup")
    st.markdown("&emsp; &emsp; 5. Alih Usaha")
    st.markdown("&emsp; &emsp; 6. Tidak Ditemukan")
    st.markdown("&emsp; &emsp; 7. Aktif Pindah")
    st.markdown("&emsp; &emsp; 8. Aktif Nonrespon")
    st.markdown("&emsp; &emsp; 9. Duplikat")
    st.markdown("&emsp; &emsp; 10. Salah Kode Wilayah")
    st.text("b. idsbr_master")
    st.markdown("&emsp; &emsp; diisi jika keberadaan_usaha = 9")
    st.text("c. kdprov_pindah")
    st.markdown("&emsp; &emsp; diisi jika keberadaan_usaha = 7")
    st.text("d. kdkab_pindah")
    st.markdown("&emsp; &emsp; diisi jika keberadaan_usaha = 7")

    st.subheader("Wilayah Usaha/Perusahaan")
    st.text("a. kdprov")
    st.text("b. kdkab")
    st.text("c. kdkec")
    st.text("d. kddesa")

    st.subheader("Karakteristik Usaha/Perusahaan")
    st.text("a. jenis_kepemilikan_usaha")
    st.markdown("&emsp; &emsp; 1. BUMN")
    st.markdown("&emsp; &emsp; 2. Non BUMN")
    st.markdown("&emsp; &emsp; 3. BUMD")
    st.markdown("&emsp; &emsp; 4. BUMDes")
    st.text("b. bentuk_badan_hukum_usaha")
    st.markdown("&emsp; &emsp; 1. Perseroan (PT/ PT Persero..)")
    st.markdown("&emsp; &emsp; 2. Yayasan")
    st.markdown("&emsp; &emsp; 3. Koperasi")
    st.markdown("&emsp; &emsp; 4. Dana Pensiun")
    st.markdown("&emsp; &emsp; 5. Perum/Perumda")
    st.markdown("&emsp; &emsp; 6. BUM Desa")
    st.markdown("&emsp; &emsp; 7. CV")
    st.markdown("&emsp; &emsp; 8. Firma")
    st.markdown("&emsp; &emsp; 9. Persekutuan Perdata (Maatschap)")
    st.markdown("&emsp; &emsp; 10. Kantor Perwakilan Luar Negeri")
    st.markdown("&emsp; &emsp; 11. Badan Usaha Luar Negeri")
    st.markdown("&emsp; &emsp; 12. Usaha Orang Perseorangan")
    st.markdown("&emsp; &emsp; 99. Lainnya")
    st.text("c. deskripsi_badan_usaha_lainnya")
    st.markdown("&emsp; &emsp; diisi jika bentuk_badan_hukum_usaha = 99")
    st.text("d. tahun_berdiri")
    st.text("e. jaringan_usaha")
    st.markdown("&emsp; &emsp; 1. Tunggal")
    st.markdown("&emsp; &emsp; 2. Kantor Pusat")
    st.markdown("&emsp; &emsp; 3. Kantor Cabang")
    st.markdown("&emsp; &emsp; 4. Perwakilan")
    st.markdown("&emsp; &emsp; 5. Pabrik/Unit Kegiatan")
    st.markdown("&emsp; &emsp; 6. Unit Pembantu/Penunjang")
    st.text("f. sektor_institusi")
    st.markdown("&emsp; &emsp; 1. S11 – Korporasi Finansial")
    st.markdown("&emsp; &emsp; 2. S12 – Korporasi Non Finansial")
    st.markdown("&emsp; &emsp; 3. S13 – Pemerintahan Umum")
    st.markdown("&emsp; &emsp; 4. S14 – Rumah Tangga")
    st.markdown("&emsp; &emsp; 5. S15 – LNPRT")

    st.subheader("Kegiatan Usaha/Perusahaan")
    st.text("a. deskripsi_kegiatan_usaha")
    st.text("b. kategori")
    st.text("c. kbli")
    st.text("d. produk_usaha")

    st.subheader("Lain Lain")
    st.text("a. sumber_profiling")
    st.text("b. catatan_profiling")
